In [1]:
import pandas as pd
import numpy as np
import dateutil
import calendar

# package to extract data from various Internet sources into a DataFrame
# make sure you have it installed
from pandas_datareader import data, wb

# package for dates
import datetime as dt

In [2]:
A_vendor_weigh = pd.read_csv('Xiaomi_5weeks.csv')

In [3]:
#데이터 타임으로 변경
A_vendor_weigh['Date'] = pd.to_datetime(A_vendor_weigh.loc[:,'Date'])
A_vendor_weigh

,Unnamed: 0,Vendor,Product_name,Date,Week,Year,Point,Vote,Title,Review
0,810,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,good
1,811,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,Really the product is awesome and notchless w...
2,812,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,just amazing was really waiting for a piece l...
3,813,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,Excellent Device
4,814,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,awesome mobile.....
5,815,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,awesome device.
6,816,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,The Greatest of all...!!! You smashed the mar...
7,817,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,superb phone
8,818,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,awesome phone
9,819,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,very good phone. super performer.,best mobile in market.
10,820,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,good phone
11,821,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,I've fallen in love!This is great phone. Deli...
12,822,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,Feels smooth and elegant.
13,823,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,Everything loaded tightly with more features ...
14,824,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,awesome
15,825,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,good
16,826,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,Alrounder. Just unbelievable product
17,827,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,superb phone
18,828,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,nice one
19,829,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,wow. colour superb. pop up avesome
20,830,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,A unbelievable machine...... it's best for th...
21,831,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,Super happy with the purchase!,The best mobile you'll find below 35000. The ...
22,832,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,"One of the best device i have ever used, 28k ..."
23,833,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,"Best Quality, Good Looks & Really Value For Mo...","Best Quality, Good Looks & Really Value For M..."
24,834,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,I never felt so happy habdling any electronic...
25,835,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!super mobile at that price...,I just loved this phone
26,836,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,damn awesome
27,837,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love!,owsam prodeuct
28,838,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,0,I've fallen in love! awesome,awesome product!
29,839,Xiaomi,Redmi K20 Pro,2019-07-28,30,19,5,1,Its great,The phone is worth every penny
...,...,...,...,...,...,...,...,...,...,...
37784,114822,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,Best phone at this price range.
37785,114823,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,no,better
37786,114824,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,awesome mobile
37787,114825,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,good expression for dish phone osam love you ...
37788,114826,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,nyc
37789,114827,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,nyc
37790,114828,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,I'm very happy
37791,114829,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,nice
37792,114830,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,good Phone for this price
37793,114831,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,good and amazing performance.
37794,114832,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,it's awesome phone
37795,114833,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,good product,good product
37796,114834,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,great
37797,114835,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love,I've fallen in love
37798,114836,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,This is best phone in best price with good del...,This is best phone in best price with good de...
37799,114837,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,wonderful
37800,114838,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,This is so beautiful..
37801,114839,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,Simply Great..!!,Simply Great..!!
37802,114840,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,5,0,I've fallen in love!,Great..!!
37803,143035,Xiaomi,Redmi 6 Pro,2019-08-24,34,19,4,0,I'm pretty happy with this product,NYC product
37804,143036,Xiaomi,Redmi 6 Pro,2019-08-24,34,19,4,0,Im pretty happy with this product,Nice phone
37805,143037,Xiaomi,Redmi 6 Pro,2019-08-24,34,19,4,0,I'm pretty happy with this product,good phone
37806,143038,Xiaomi,Redmi 6 Pro,2019-08-24,34,19,4,0,good,good phone value for money
37807,143039,Xiaomi,Redmi 6 Pro,2019-08-23,34,19,4,0,Im pretty happy with this product,good phone
37808,143040,Xiaomi,Redmi 6 Pro,2019-08-20,34,19,4,0,I'm pretty happy with this product superb,superb
37809,143041,Xiaomi,Redmi 6 Pro,2019-08-20,34,19,4,0,I'm pretty happy with this product,good.
37810,143042,Xiaomi,Redmi 6 Pro,2019-08-20,34,19,4,0,Nice One!,The mobile is pretty awesome.
37811,143043,Xiaomi,Redmi 6 Pro,2019-08-19,34,19,4,0,Valuable,Nice Phone
37812,144221,Xiaomi,Redmi 6 Pro,2019-08-21,34,19,3,0,Not a bad choice,Good
37813,144222,Xiaomi,Redmi 6 Pro,2019-08-20,34,19,3,0,Not a bad choice,it's really nice phone I loved tQ ...

In [4]:
#두 컬럼만 불러오기
A_vendor_weigh = A_vendor_weigh[['Date', 'Vendor']]
A_vendor_weigh.head()

        Date  Vendor
0 2019-07-28  Xiaomi
1 2019-07-28  Xiaomi
2 2019-07-28  Xiaomi
3 2019-07-28  Xiaomi
4 2019-07-28  Xiaomi

In [5]:
# 내림차순으로 정렬
A_vendor_weigh = A_vendor_weigh.sort_values(['Date'], ascending=[False])

In [6]:
# 데이트 뉴, 앞으로 설정
A_vendor_weigh = A_vendor_weigh.set_index('Date')

In [7]:
#주차별로 멀티 인덱스 만들기
A_vendor_weigh1 = A_vendor_weigh.groupby(['Vendor','Date']).resample('w').count().unstack()
A_vendor_weigh1.head()

                      Vendor
Date              2019-07-28 2019-08-04 2019-08-11 2019-08-18 2019-08-25
Vendor Date
Xiaomi 2019-07-22     1707.0        NaN        NaN        NaN        NaN
       2019-07-23     2651.0        NaN        NaN        NaN        NaN
       2019-07-24     1605.0        NaN        NaN        NaN        NaN
       2019-07-25     1628.0        NaN        NaN        NaN        NaN
       2019-07-26     1855.0        NaN        NaN        NaN        NaN

In [8]:
#결측값 = 0 처리
A_vendor_weigh1 = A_vendor_weigh1.fillna(0)

In [9]:
#데이트 뉴 행으로 합치기 
A_vendor_weigh2 = A_vendor_weigh1.sum(axis=1, level = 'Date')
A_vendor_weigh2

Date               2019-07-28  2019-08-04  2019-08-11  2019-08-18  2019-08-25
Vendor Date
Xiaomi 2019-07-22      1707.0         0.0         0.0         0.0         0.0
       2019-07-23      2651.0         0.0         0.0         0.0         0.0
       2019-07-24      1605.0         0.0         0.0         0.0         0.0
       2019-07-25      1628.0         0.0         0.0         0.0         0.0
       2019-07-26      1855.0         0.0         0.0         0.0         0.0
       2019-07-27      1524.0         0.0         0.0         0.0         0.0
       2019-07-28      1651.0         0.0         0.0         0.0         0.0
       2019-07-29         0.0       849.0         0.0         0.0         0.0
       2019-07-30         0.0       978.0         0.0         0.0         0.0
       2019-07-31         0.0      1181.0         0.0         0.0         0.0
       2019-08-01         0.0      1061.0         0.0         0.0         0.0
       2019-08-02         0.0      1151.0         0.0         0.0         0.0
       2019-08-03         0.0      1091.0         0.0         0.0         0.0
       2019-08-04         0.0       808.0         0.0         0.0         0.0
       2019-08-05         0.0         0.0       749.0         0.0         0.0
       2019-08-06         0.0         0.0       997.0         0.0         0.0
       2019-08-07         0.0         0.0       901.0         0.0         0.0
       2019-08-08         0.0         0.0      1084.0         0.0         0.0
       2019-08-09         0.0         0.0       902.0         0.0         0.0
       2019-08-10         0.0         0.0       922.0         0.0         0.0
       2019-08-11         0.0         0.0       988.0         0.0         0.0
       2019-08-12         0.0         0.0         0.0       977.0         0.0
       2019-08-13         0.0         0.0         0.0       919.0         0.0
       2019-08-14         0.0         0.0         0.0       937.0         0.0
       2019-08-15         0.0         0.0         0.0       836.0         0.0
       2019-08-16         0.0         0.0         0.0       908.0         0.0
       2019-08-17         0.0         0.0         0.0       943.0         0.0
       2019-08-18         0.0         0.0         0.0       903.0         0.0
       2019-08-19         0.0         0.0         0.0         0.0       811.0
       2019-08-20         0.0         0.0         0.0         0.0       957.0
       2019-08-21         0.0         0.0         0.0         0.0       865.0
       2019-08-22         0.0         0.0         0.0         0.0       676.0
       2019-08-23         0.0         0.0         0.0         0.0       235.0
       2019-08-24         0.0         0.0         0.0         0.0       838.0
       2019-08-25         0.0         0.0         0.0         0.0       726.0

In [10]:
#주+벤더별 정렬하기
A_vendor_weigh3 = A_vendor_weigh2.sum(axis=0, level = 'Vendor')
A_vendor_weigh3

Date    2019-07-28  2019-08-04  2019-08-11  2019-08-18  2019-08-25
Vendor
Xiaomi     12621.0      7119.0      6543.0      6423.0      5108.0

In [11]:
# 칼럼명 변경
A_vendor_weigh3.columns = ["Week30", "Week31", "Week32", "Week33", "Week34"]
A_vendor_weigh3

         Week30  Week31  Week32  Week33  Week34
Vendor
Xiaomi  12621.0  7119.0  6543.0  6423.0  5108.0

In [12]:
#가중치 더해서 weight_sum하기
A_vendor_weigh3["Week34"] = A_vendor_weigh3["Week34"] * (0.95)
A_vendor_weigh3["Week33"] = A_vendor_weigh3["Week33"] * (0.90)
A_vendor_weigh3["Week32"] = A_vendor_weigh3["Week32"] * (0.85)
A_vendor_weigh3["Week31"] = A_vendor_weigh3["Week31"] * (0.80)
A_vendor_weigh3["Week30"] = A_vendor_weigh3["Week30"] * (0.75)

A_vendor_weigh3

         Week30  Week31   Week32  Week33  Week34
Vendor
Xiaomi  9465.75  5695.2  5561.55  5780.7  4852.6

In [13]:
#칼럼명으로 오름차순 정렬

A_vendor_weigh3 = A_vendor_weigh3.sort_index(axis =1 , ascending = True)

In [14]:
####################################################
#####주차별 가중치합 (기존의 Weight_sum과 달리, 2~4주차치만 뽑은 데이터!)

A_vendor_weigh3['Weight_sum'] = A_vendor_weigh3['Week34'] + A_vendor_weigh3['Week33'] + A_vendor_weigh3['Week32'] + A_vendor_weigh3['Week31'] + A_vendor_weigh3['Week30']
A_vendor_weigh3

         Week30  Week31   Week32  Week33  Week34  Weight_sum
Vendor
Xiaomi  9465.75  5695.2  5561.55  5780.7  4852.6     31355.8

In [15]:
# csv파일로 저장하기
data = pd.DataFrame(A_vendor_weigh3)
data.to_csv('Xiaomi_vendor_weight_sum.csv')